### PR TITLE
Fix "unknown option: --Python" issue

### PR DESCRIPTION
**Pull request by JumpingYang001**
Current built out message shows "unknown option: --Python", just fix it, thanks.
@Microsoft/omi-devs, @alinbalutoiu ,@c64cosmin  ,help review it if you are free, thanks very much!

Issue:
```
/opt/omi/bin/omireg --Python XYZ_Frog
/opt/omi/bin/omireg: unknown option: --Python
```

### CODE REVIEW

**Comment by alinbalutoiu** [comment]
For me it works without this. Are you sure this is needed? Could you please post the steps on how to reproduce it?

**Comment by JumpingYang001** [comment]
@alinbalutoiu, Install .deb or .rpm package, you will see the omireg.conf contains
`script=\-\-python:python2.7:client.p
script=\-\-Python:python2.7:client.p`
and you will get "unknown option: --Python", are you using package but not building source code one?

**Comment by alinbalutoiu** [comment]
Ah, I just noticed this was from the package, I was building from source.
Looks good to me.

**Comment by JumpingYang001** [comment]
@alinbalutoiu help me approve this PR, thanks.

**Review by alinbalutoiu — APPROVED** [review]

**Pull request merged**
