### PR TITLE
Add required schema files to data files

### PR DESCRIPTION
**Pull request by alinbalutoiu**
omigen_py requires omischema to be present,
otherwise it will fail when searching for the mof files.

Closes issue #10

### CODE REVIEW

**Comment by alinbalutoiu** [comment]
Do you guys know a way to copy the whole folder with a single line? The only solution that I found was to specify individually each file which needs to be copied.

**Review by JumpingYang001 — APPROVED** [review]
You are right, we have to list all files want to pack, thanks.
No other easy way like pattern match.

**Comment by JumpingYang001** [comment]
@jeffaco, do you know if there is a way to copy the whole folder with a single line for installer script?

**Review by jeffaco — CHANGES_REQUESTED** [review]
I suggest that this PR be scrapped.

Discussion yesterday, in the scrum, reached consensus that if you want to build a provider from scratch, you need to build OMI from source. That's the way it is for C++ and/or C, and that's how it'll be for Python as well.

Note that this is only needed for omigen. Once you have the Python scripts generated, you can change them without OMI source builds. But to run omigen, you need OMI source builds.

Also, to do this "right", we would have a separate -dev kit (i.e. `omi` to install OMI, and `omi-dev` to install OMI development tools). We have considered this in the past but it never made it to the top of the heap of things to work on.

To answer your other question: There is not a way to copy a lot of independent files without specifying them, one by one. This is because the native installers themselves require individual lists of files. We have, however, at times resorted to [install builder data file generators](https://github.com/Microsoft/OMS-Agent-for-Linux/blob/master/installer/scripts/genRubyInstaller.sh), to install Ruby for example.

**Comment by jeffaco** [comment]
One more thing: The OMI script provider should not ever install OMI bits. OMI is responsible for OMI, and the OMI script generator is responsible for the OMI script generator. Violating this can cause (very) major problems down the road (been there, done that).

**Pull request closed without merging**
