### PR TITLE
Add different Python versions support

### PR DESCRIPTION
**Pull request by alinbalutoiu**
The Python wrapper is compatible with all the versions of Python starting from Python 2.6 upwards.

This commit replaces the python2.7 command with python which will default to the environment default Python version.

### CODE REVIEW

**Comment by alinbalutoiu** [comment]
Any idea on how to replace the file from this line: https://github.com/Microsoft/omi-script-provider/blob/master/installbuilder/Base_OMIScriptProvider.data#L15 with another one depending on a variable?
Python 3 has different name conventions which were introduced by http://legacy.python.org/dev/peps/pep-3149/ and the filename has some specific build text between ```omi``` and ```.so``` , example: ```omi.cpython-34m.so``` or ```cpython-34m-x86_64-linux-gnu``` etc.

Building release packages for Python 3 work if the library gets modified manually to ```omi.so```, we need to find a way to fix the above.

**Review by EMumau — DISMISSED** [review]
Changing the GNUmakefile(s), install scripts, and the shebang in client.py to use the default installed version of python that's available on the server should be changed.  For our own internal purposes, that will make it difficult to test each supported version of python on a server that has many versions of python installed.
I suggest that you add something like a "--version=[pythonx.x]" option to the configure script that sets a variable that is used instead of "python" in the GNUmakefiles, shebang, and install scripts.

**Comment by alinbalutoiu** [comment]
I did also a quick test with a package built for Python 3.6 and it looks good.
```
ubuntu@ubuntu:~$ sudo dpkg -i OMIScriptProvider-1.1.1-61.Python-3.6.x64.deb
Selecting previously unselected package omiscriptprovider.
(Reading database ... 62716 files and directories currently installed.)
Preparing to unpack OMIScriptProvider-1.1.1-61.Python-3.6.x64.deb ...
Unpacking omiscriptprovider (1.1.1.61) ...
Setting up omiscriptprovider (1.1.1.61) ...
ubuntu@ubuntu:~$ python3.6
Python 3.6.3 (default, Oct  6 2017, 08:44:35)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import omi
>>>
```

**Review by c64cosmin — APPROVED** [review]
LGTM

**Pull request merged**
